version: "3"
services:
    dating-social-network:
        build: .
        ports:
            - 5000:3000
        env_file:
            - system.env
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        links:
            - database

    database:
        image: "mariadb"
        env_file:
          - system.env

