version: "3"
services:
    dating:
        build: .
        ports:
            - 5000:5000
        env_file:
            - .env
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        links:
            - database

    database:
        image: "mariadb"
        ports:
            - 3306:3306
        env_file:
          - .env
